{
    "body": "```\r\nException occurred:\r\n  File \"/spack/a-saitoh/spack/spack/opt/spack/linux-rhel8-a64fx/gcc-8.3.1/py-nbconvert-6.0.7-asymoummz5thrbum3y5oia2c42fmucao/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py\", line 601, in get_template_names\r\n    raise ValueError('No template sub-directory with name %r found in the following paths:\\n\\t%s' % (base_template, paths))\r\nValueError: No template sub-directory with name 'rst' found in the following paths:\r\n        /spack/a-saitoh/.local/share/jupyter\r\n        /spack/a-saitoh/spack/spack/opt/spack/linux-rhel8-a64fx/gcc-8.3.1/python-3.8.7-zxyihcxyc4iy2g2ha7yltrjyq3l7iz4t/share/jupyter\r\n        /usr/local/share/jupyter\r\n        /usr/share/jupyter\r\nThe full traceback has been saved in /spack/a-saitoh/sphinx-err-_2w_19j2.log, if you want to report the issue to the developers.\r\nPlease also report this if it was a user error, so that a better error message can be provided next time.\r\nA bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!\r\nmake: *** [Makefile:20: html] Error 2\r\n```\r\nThere was a problem that the jupyter template could not be loaded. I fixed to add the path where the file exists to `JUPYTER_PATH`.",
    "user": "t-karatsu",
    "url": "https://api.github.com/repos/spack/spack/issues/21827",
    "updated_at": "2021-02-22 00:09:08",
    "created_at": "2021-02-21 08:44:11",
    "closed_at": "2021-02-21 17:13:23",
    "state": "closed",
    "title": "py-nbconvert: add function 'setup_dependent_build_environment'.",
    "number": 21827,
    "milestone": null,
    "labels": [
        "run-environment"
    ],
    "id": 812805580,
    "html_url": "https://github.com/spack/spack/pull/21827",
    "assignees": [],
    "comments": 0
}