{
    "body": "Our exception handler currently raises an exception of its own when handling an error in a `filter_file` operation. Because the temp file is removed in the `finally` block, we should not remove it in the `except` block.\r\n\r\nThis removes the first call to remove the file, now the code reports the appropriate exception from `filter_file`",
    "user": "becker33",
    "url": "https://api.github.com/repos/spack/spack/issues/14651",
    "updated_at": "2020-06-30 23:38:54",
    "created_at": "2020-01-28 19:17:48",
    "closed_at": "2020-01-28 20:49:27",
    "state": "closed",
    "title": "Fix handling of filter_file exceptions",
    "number": 14651,
    "milestone": null,
    "labels": [],
    "id": 556413066,
    "html_url": "https://github.com/spack/spack/pull/14651",
    "assignees": [],
    "comments": 0
}